import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'

import { StyledRegistry } from '@/lib/styled/styled-registry'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        <StyledRegistry>{children}</StyledRegistry>
      </body>
    </html>
  )
}
