import type { Metadata } from 'next'

import { fonts, StyledRegistry } from '@/lib/styled/styled-registry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={fonts}>
        <StyledRegistry>{children}</StyledRegistry>
      </body>
    </html>
  )
}
