name: Build and Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build 
        run: |
          npm install --frozen-lockfile
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          token: ${{ secrets.TOKEN }}
          folder: storybook-static
          clean: true